### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by kiltro-dev** [devfullcycle/fc-event-quickstart#4]
Este comando `$ sudo rm -rf /usr/local/go && tar -C /usr/local -xzf go1.20.4.linux-amd64.tar.gz`  dá permissão negada, acho que é porque o sudo está faltando antes do tar. Eu os executei com sudo ambos, mas separadamente e tive sucesso. Seria bom retirar o sinal $ dos comandos para não copiá-lo.

**Comment by argentinaluiz** [comment]
Olá @kiltro-dev , sim preciso de um sudo antes do tar, porque ele descompacta dentro da /usr/local.

Vamos atualizar o README.md.

Obrigado pelo contribuição!
